name: Docker Build and Push with Yaml Update

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/simple-web
  YAML_REPO: ${{ secrets.YAML_REPO }}
  PAT: ${{ secrets.PAT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.slug.outputs.sha8 }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Checkout yaml repo
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          repository: ${{ env.YAML_REPO }}
          token: ${{ env.PAT }}
          path: yaml-repo

      - name: Update image tag in yaml repo
        if: github.event_name != 'pull_request'
        run: |
          cd yaml-repo
          sed -i "s|\(image: ${{ env.DOCKER_HUB_USERNAME }}/simple-web\).*|\1:${{ steps.slug.outputs.sha8 }}|" simple-deploy.yaml
          
          git diff

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add simple-deploy.yaml
          git commit -m "Update image tag to ${{ steps.slug.outputs.sha8 }}"
          git push